/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Date = bigint;
export interface Expense {
  'id' : bigint,
  'isSettled' : boolean,
  'date' : Date,
  'item' : string,
  'friendId' : [] | [bigint],
  'amount' : number,
  'paidBy' : string,
}
export interface Friend {
  'id' : bigint,
  'name' : string,
  'totalLent' : number,
  'totalBorrowed' : number,
}
export interface Settlement {
  'id' : bigint,
  'direction' : string,
  'date' : Date,
  'friendId' : bigint,
  'amount' : number,
}
export interface Summary {
  'totalLent' : number,
  'friendsSummary' : Array<[bigint, number]>,
  'totalExpenses' : number,
  'totalBorrowed' : number,
  'personalExpenses' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addExpense' : ActorMethod<
    [string, number, Date, string, [] | [bigint]],
    undefined
  >,
  'addFriend' : ActorMethod<[string], bigint>,
  'addSettlement' : ActorMethod<[bigint, number, Date, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteExpense' : ActorMethod<[bigint], undefined>,
  'deleteFriend' : ActorMethod<[bigint], undefined>,
  'deleteSettlement' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExpenses' : ActorMethod<[], Array<Expense>>,
  'getFriends' : ActorMethod<[], Array<Friend>>,
  'getSettlements' : ActorMethod<[], Array<Settlement>>,
  'getSummary' : ActorMethod<[], Summary>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateExpense' : ActorMethod<
    [bigint, string, number, Date, string, [] | [bigint]],
    undefined
  >,
  'updateFriend' : ActorMethod<[bigint, string], undefined>,
  'updateSettlement' : ActorMethod<
    [bigint, bigint, number, Date, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];