/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Date = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Expense = IDL.Record({
  'id' : IDL.Nat,
  'isSettled' : IDL.Bool,
  'date' : Date,
  'item' : IDL.Text,
  'friendId' : IDL.Opt(IDL.Nat),
  'amount' : IDL.Float64,
  'paidBy' : IDL.Text,
});
export const Friend = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'totalLent' : IDL.Float64,
  'totalBorrowed' : IDL.Float64,
});
export const Settlement = IDL.Record({
  'id' : IDL.Nat,
  'direction' : IDL.Text,
  'date' : Date,
  'friendId' : IDL.Nat,
  'amount' : IDL.Float64,
});
export const Summary = IDL.Record({
  'totalLent' : IDL.Float64,
  'friendsSummary' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Float64)),
  'totalExpenses' : IDL.Float64,
  'totalBorrowed' : IDL.Float64,
  'personalExpenses' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addExpense' : IDL.Func(
      [IDL.Text, IDL.Float64, Date, IDL.Text, IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'addFriend' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'addSettlement' : IDL.Func([IDL.Nat, IDL.Float64, Date, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteExpense' : IDL.Func([IDL.Nat], [], []),
  'deleteFriend' : IDL.Func([IDL.Nat], [], []),
  'deleteSettlement' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getFriends' : IDL.Func([], [IDL.Vec(Friend)], ['query']),
  'getSettlements' : IDL.Func([], [IDL.Vec(Settlement)], ['query']),
  'getSummary' : IDL.Func([], [Summary], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateExpense' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, Date, IDL.Text, IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'updateFriend' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateSettlement' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Float64, Date, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Date = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Expense = IDL.Record({
    'id' : IDL.Nat,
    'isSettled' : IDL.Bool,
    'date' : Date,
    'item' : IDL.Text,
    'friendId' : IDL.Opt(IDL.Nat),
    'amount' : IDL.Float64,
    'paidBy' : IDL.Text,
  });
  const Friend = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'totalLent' : IDL.Float64,
    'totalBorrowed' : IDL.Float64,
  });
  const Settlement = IDL.Record({
    'id' : IDL.Nat,
    'direction' : IDL.Text,
    'date' : Date,
    'friendId' : IDL.Nat,
    'amount' : IDL.Float64,
  });
  const Summary = IDL.Record({
    'totalLent' : IDL.Float64,
    'friendsSummary' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Float64)),
    'totalExpenses' : IDL.Float64,
    'totalBorrowed' : IDL.Float64,
    'personalExpenses' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addExpense' : IDL.Func(
        [IDL.Text, IDL.Float64, Date, IDL.Text, IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'addFriend' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'addSettlement' : IDL.Func([IDL.Nat, IDL.Float64, Date, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteExpense' : IDL.Func([IDL.Nat], [], []),
    'deleteFriend' : IDL.Func([IDL.Nat], [], []),
    'deleteSettlement' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getFriends' : IDL.Func([], [IDL.Vec(Friend)], ['query']),
    'getSettlements' : IDL.Func([], [IDL.Vec(Settlement)], ['query']),
    'getSummary' : IDL.Func([], [Summary], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateExpense' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, Date, IDL.Text, IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'updateFriend' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateSettlement' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Float64, Date, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };